services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app
    command: "npm run start:dev"

  frontend:
    image: node:22-slim
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "dev"]
